# Generated by Django 3.2.16 on 2024-10-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20241024_2213'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='unique_person_constraint',
        ),
    ]
