# Generated by Django 3.2.16 on 2024-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20241028_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='Тег'),
        ),
    ]
